CREATE DATABASE STUDENTS_RECORD;

-- Creating the first table "Student Information"...

CREATE TABLE STUDENT_INFOS (
	STUDENT_ID INT NOT NULL IDENTITY (100, 1) PRIMARY KEY, 
	GENDER VARCHAR (6),
	NAME_OF_STUDENT VARCHAR (100),
	AGE INT,
	SUBJECT_OFFERED_BY_STUDENT VARCHAR (100) NOT NULL);

-- To add values to my Table...

DROP TABLE STUDENT_INFOS;

INSERT INTO STUDENT_INFOS
VALUES ('M', 'ARKMAN VICTOR', 29, 'International Business'),
	   ('F', 'REBECCA STANLEY', 23, 'Microbiology'),
	   ('F', 'PHILOPHENA SUNDAY', 26, 'Business Administration'),
	   ('M', 'SUNDAY TITUS', 22, 'Banking and Finance'),
	   ('M', 'HILARY GODSON', 34, 'International Management'),
	   ('F', 'RUTH MOARK', 23, 'International Business'),
	   ('F', 'CASSANDRA PLORA', 22, 'Busness Administration');

SELECT * FROM STUDENT_INFOS;

--The second table "Health Record"...

CREATE TABLE HEALTH_RECORDS (
	HEALTH_ID INT IDENTITY (100,1) PRIMARY KEY,
	STUDENT_ID INT NOT NULL,
	BLOOD_GROUP VARCHAR (50),
	STUDENT_HEIGHT NUMERIC (10,2),
	STUDENT_WEIGHT NUMERIC (10,2),
	FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFOS (STUDENT_ID));

DROP TABLE HEALTH_RECORDS;

INSERT INTO HEALTH_RECORDS
VALUES (104,'O+', 175, 70.5),
	   (100,'AB+', 162, 55.2),
	   (103,'B-', 155, 50.1),
	   (106,'B+', 185.5, 90.2),
	   (105,'A+', 173, 75.3),
	   (101,'O+', 185.5, 80.0),
	   (102,'AB+', 168.5, 63.7);

SELECT * FROM HEALTH_RECORDS;

--The third table "Peformance"...

CREATE TABLE PERFORMANCE (
	PERFORMANCE_ID INT IDENTITY (100,1),
	STUDENT_ID INT NOT NULL,
	GRADE NUMERIC (10,2),
	FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFOS (STUDENT_ID));

DROP TABLE PERFORMANCE;

INSERT INTO PERFORMANCE
VALUES (104, 88),
	   (106, 67),
	   (102, 70),
	   (103, 95),
	   (100, 48),
	   (101, 54),
	   (105, 70);

SELECT * FROM STUDENT_INFOS
SELECT * FROM HEALTH_RECORDS
SELECT * FROM PERFORMANCE;

--Renamed the SUBJECT_OFFERED_BY_STUDENT to COURSE...

EXEC sp_rename 'STUDENT_INFOS.SUBJECT_OFFERED_BY_STUDENT', 'COURSE', 'COLUMN';

--To drop the AGE column from the STUDENT_INFOS Table....

ALTER TABLE STUDENT_INFOS DROP COLUMN AGE;

SELECT * FROM STUDENT_INFOS;
